spring:
  application:
    name: foobarquix
  datasource:
    url: jdbc:h2:mem:foobarquixdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    initialize-schema: always
    job:
      enabled: false

batch:
  input-file: input.txt
  output-file: output.txt

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework: INFO

org.hibernate.type.descriptor.sql.BasicBinder: TRACE
