spring:
  application:
    name: foobarquix
  datasource:
    url: jdbc:h2:mem:foobarquixdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    initialize-schema: always
